# See https://cloud.google.com/workflows/docs/run/tutorial-cloud-run
main:
    params: [args]
    steps:
    - autotranscoder:
        call: http.post
        args:
            url: https://autotranscoder-aviwqsvtfq-uc.a.run.app
            body:
                sourceBucket: ${args.sourceBucket}
                sourceVideoPath: ${args.sourceVideoPath}
                targetWidth: ${args.targetWidth}
                targetHeight: ${args.targetHeight}
                startTimeOffsetSeconds: ${args.startTimeOffsetSeconds}
                intervalSeconds: ${args.intervalSeconds}
        result: autotranscoderResult
    - waitForTranscodingComplete:
        call: waitForJobCompletion
        args:
            jobName: ${autotranscoderResult.body.JobName}
    - dropletDetector:
        call: http.post
        args:
            url: https://droplet-detector-aviwqsvtfq-uc.a.run.app
            body:
                bucket: ${autotranscoderResult.body.TargetBucket}
                dir_path: ${autotranscoderResult.body.TargetDirPath}
        result: dropletDetectorResult
    - return_result:
        return: ${dropletDetectorResult}

# See https://cloud.google.com/workflows/docs/sleeping
waitForJobCompletion:
    params: [jobName]
    steps:
    - wait1:
        call: sys.sleep
        args:
            seconds: 10
        next: checkJob
    - checkJob:
        call: http.get
        args:
            url: ${"https://transcoder.googleapis.com/v1beta1/" + jobName}
            auth:
                type: OAuth2
        result: jobResponse
    - checkIfDone:
        switch:
          - condition: ${jobResponse.body.state == "SUCCEEDED"}
            return: jobResponse
    - wait2:
        call: sys.sleep
        args:
            seconds: 60
        next: checkJob
